openapi: 3.0.3
info:
  title: ImageStorageService API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /upload:
    post:
      summary: Upload a file
      description: Upload a file
      operationId: uploadFile
      requestBody:
        description: The file to be uploaded
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: File uploaded successfully
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Bad request, no file uploaded
          content:
            text/plain:
              schema:
                type: string
              example: No file uploaded.
