version: '3.8'

services:
  rabbitmq:
    container_name: message-broker-service
    image: "rabbitmq:management"
    ports:
      - "5672:5672"  # RabbitMQ default AMQP port
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - some-net

networks:
  some-net:
    name: giveItANamePlease
    driver: bridge