version: '3.8'

services:
  image-generator-service:
    container_name: image-generator-service
    image: custom-openmadriva
    build:
      dockerfile: Dockerfile
    networks:
      - my-proxy-net

networks:
  my-proxy-net:
    name: giveItANamePlease
    external: true