version: '3.8'

services:
  image-generator-service:
    container_name: image-generator-service
    image: custom-openmadriva
    build:
      dockerfile: Dockerfile
    volumes:
      - ./build:/app
    networks:
      - my-proxy-net
    command: ["/app/image-generator-service"]

networks:
  my-proxy-net:
    name: rabbitmq-network
    external: true